version: 3.5.1.{build}
image: Visual Studio 2019
environment:
  push_to_nuget: true
nuget:
  project_feed: true
before_build:
- cmd: nuget restore Npoi.Mapper\Npoi.Mapper.sln
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: MyNupkg
configuration: Debug

# here we are going to override common configuration
for:

# configuration for "master" branch
# build in Release mode and deploy to NuGet
-
  branches:
    only:
      - master
  configuration: Release
  deploy:
    provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: XdYQJ8lrlNPh1kg2NsGMVJMKaNojTQ6/ckBLy1/CiL2y9Ku1a3b8kr/XgLg86MKu
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: MyNupkg
    on:
      push_to_nuget: true
